language: python
python:
    - 3.5

services: postgresql

env:
    - DJANGO=1.10

before_install:
    - export DJANGO_SETTINGS_MODULE="ecommerce_project.settings"
    - export PYTHONPATH="$HOME/builds/joegotflow83/travis-ci-ecommerce"

install:
    - pip install -r requirements.txt
    - pip install psycopg2 --quiet
    - pip install coveralls radon

before_script:
    - psql -c "CREATE DATABASE mydb;" -U postgres

script: ./manage.py test
